apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecs-pg-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "mnt/data"
