apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecs-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecs-client
  template:
    metadata:
      labels:
        app: ecs-client
    spec:
      containers:
        - name: ecs-client
          image: unknown/ecs-client
