apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ecs
  name: ecs-pg-db-depl
spec:
  serviceName: ecs-pg-db
  replicas: 2
  selector:
    matchLabels:
      app: ecs-pg-db
  template:
    metadata:
      labels:
        app: ecs-pg-db
    spec:
      containers:
        - name: ecs-pg-db
          image: bitnami/postgresql:12
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ecs-pg-db-secret
                  key: db-name
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecs-pg-db-secret
                  key: db-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecs-pg-db-secret
                  key: db-password
          volumeMounts:
            - name: ecs-pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: ecs-pg-data
          persistentVolumeClaim:
            claimName: ecs-pg-claim
