apiVersion: v1
kind: Service
metadata:
  namespace: ecs
  name: ecs-server-svc
spec:
  selector:
    app: ecs-server
  ports:
    - name: ecs-server
      protocol: TCP
      port: 1337
      targetPort: 1337
